### ISSUE TITLE
error

### ISSUE THREAD

**Issue by 1ndianl33t** [Sh1Yo/rate-limit-checker#1]
$ rate 

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x555585a3a4]

goroutine 1 [running]:
main.main()
        /data/data/com.termux/files/home/src/github.com/Sh1Yo/rate-limit-checker/rate.go:32 +0x3ec

**Comment by Sh1Yo** [comment]
@1ndianl33t Can you check whether the new commit fixed the issue or not?

**Comment by 1ndianl33t** [comment]
not fixed

**Comment by Sh1Yo** [comment]
@1ndianl33t Did you update the program? If yes then send me the error

**Comment by 1ndianl33t** [comment]
Yo update same error

**Comment by Sh1Yo** [comment]
Should be fixed by the last change
